using Tyuiu.StachinskiiVS.Sprint4.Task6.V8.Lib;

DataService ds = new DataService();
Console.Title = "Спринт #4 │ Выполнил: Стачинский В.С. │ ИCПб-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #4                                                               *");
Console.WriteLine("* Тема: Двумерные массивы (случайная генерация)                           *");
Console.WriteLine("* Задание #6                                                              *");
Console.WriteLine("* Вариант #8                                                              *");
Console.WriteLine("* Выполнил: Стачинский В.С. │ ИCПб-24-1                                   *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Вывести слова длинной                                                   *");
Console.WriteLine("* больше 4                                                                *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("Пицца, Борщ, Пельмени, Омлет, Салат, Суп, Роллы");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
Console.ReadKey();
string[] array = new string[] { "Пицца", "Борщ", "Пельмени", "Омлет", "Салат", "Суп", "Роллы" };
var res = ds.Calculate(array);
Console.WriteLine("[{0}]", string.Join(", ", res));
Console.ReadKey();